# This is a basic workflow to help you get started with Actions

name: ActiveMQ_Artemis_Container_Image

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - Artemis*
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build and push Docker images
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          path: ./artemis_container
          dockerfile: ./artemis_container/Dockerfile 
          build_args: BASE_IMAGE=debian
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mlehmann007/samples
          tags: Artemis-2.14.0
